# Generated by Django 4.2.1 on 2023-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_comment_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
