# Generated by Django 4.1.7 on 2023-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_comment_modify_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
